ci: improve the daily workflow

diff --git a/scripts/update-devcontainer-dockerfile b/scripts/update-devcontainer-dockerfile
--- a/scripts/update-devcontainer-dockerfile
+++ b/scripts/update-devcontainer-dockerfile
@@ -3,6 +3,7 @@
 PROGNAME=$(basename $0)
 BASEDIR=$(cd $(dirname $0); pwd)
 PROJDIR=$(cd $BASEDIR/..; pwd)
+TARGET_FILE=.devcontainer/Dockerfile
 
 if [ "$(uname)" != Linux ] || id -nG | grep -q docker; then
   DOCKER='docker'
@@ -37,6 +38,7 @@ clean() {
     $DOCKER image rm -f $IMAGE >/dev/null
     echo "Removed $IMAGE"
   fi
+  rm -f $TEMP_FILE
 }
 
 while [ $# -gt 0 ]
@@ -55,6 +57,13 @@ do
   esac
 done
 
+if [ "$(pwd)" != "$PROJDIR" ]
+then
+  echo "ERROR: must run in the project root"
+  exit 1
+fi
+
+TEMP_FILE=$(mktemp)
 trap "clean" EXIT INT TERM
 
 echo "Downloading $IMAGE..."
@@ -66,16 +75,27 @@ COMMIT_HASH=$($DOCKER run --rm $IMAGE rustc -vV | grep 'commit-hash' | cut -d ' 
 echo "Getting the path of the default toolchain contained in $IMAGE..." >&2
 TOOLCHAIN_PATH=$($DOCKER run --rm $IMAGE rustup toolchain list -v | grep '(default)' | cut -f 2)
 
-echo "Updating sourcemap variables in $PROJDIR/.devcontainer/Dockerfile..." >&2
-# Use `|` instead of `/` because TOOLCHAIN_PATH contains `/`.
-sed -e "s|^ENV MIRAKC_DEV_RUSTC_COMMIT_HASH=.*|ENV MIRAKC_DEV_RUSTC_COMMIT_HASH=\"$COMMIT_HASH\"|" \
-    -e "s|^ENV MIRAKC_DEV_RUST_TOOLCHAIN_PATH=.*|ENV MIRAKC_DEV_RUST_TOOLCHAIN_PATH=\"$TOOLCHAIN_PATH\"|" \
-    $PROJDIR/.devcontainer/Dockerfile | sponge $PROJDIR/.devcontainer/Dockerfile
-
 cat <<EOF
-Done.
 --------------------------------------------------------------------------------
 COMMIT_HASH   : $COMMIT_HASH
 TOOLCHAIN_PATH: $TOOLCHAIN_PATH
 --------------------------------------------------------------------------------
 EOF
+
+echo "Updating sourcemap variables in $TARGET_FILE..." >&2
+# Don't use the -i option of `sed`.
+# The incompatibility between macOS and GNU will cause troubles.
+#
+# Use `|` instead of `/` because TOOLCHAIN_PATH contains `/`.
+sed -e "s|^ENV MIRAKC_DEV_RUSTC_COMMIT_HASH=.*|ENV MIRAKC_DEV_RUSTC_COMMIT_HASH=\"$COMMIT_HASH\"|" \
+    -e "s|^ENV MIRAKC_DEV_RUST_TOOLCHAIN_PATH=.*|ENV MIRAKC_DEV_RUST_TOOLCHAIN_PATH=\"$TOOLCHAIN_PATH\"|" \
+    $TARGET_FILE >$TEMP_FILE
+mv -f $TEMP_FILE $TARGET_FILE
+
+if git diff --quiet -- $TARGET_FILE
+then
+  echo "Not changed"
+else
+  git add $TARGET_FILE
+  git commit -m "build: update $TARGET_FILE"
+fi
diff --git a/scripts/update-mirakc-arib b/scripts/update-mirakc-arib
--- a/scripts/update-mirakc-arib
+++ b/scripts/update-mirakc-arib
@@ -1,21 +1,25 @@
 #!/bin/sh -eu
 
-BASEDIR=$(cd $(dirname $0); pwd)
-PROJDIR=$(cd $BASEDIR/..; pwd)
-TARGET_FILE=$PROJDIR/docker/build-scripts/mirakc-arib.sh
+PROJDIR=$(cd $(dirname $0)/..; pwd)
+TARGET_FILE=docker/build-scripts/mirakc-arib.sh
 
-CURRENT=$(grep 'MIRAKC_ARIB_VERSION=' docker/build-scripts/mirakc-arib.sh | \
-            cut -d '=' -f 2 | tr -d '"')
+if [ "$(pwd)" != "$PROJDIR" ]
+then
+  echo "ERROR: must run in the project root"
+  exit 1
+fi
+
+CURRENT=$(grep 'MIRAKC_ARIB_VERSION=' $TARGET_FILE | cut -d '=' -f 2 | tr -d '"')
 
 URL='https://api.github.com/repos/mirakc/mirakc-arib/tags'
 VERSION="$(curl -fsSL $URL | jq -r '.[0].name')"
 
 TEMP_FILE=$(mktemp)
-trap "rm -f $TEMP_FILE" EXIT
+trap "rm -f $TEMP_FILE" EXIT INT TERM
 
 # Don't use the -i option of `sed`.
 # The incompatibility between macOS and GNU will cause troubles.
-sed -r -e "s|^MIRAKC_ARIB_VERSION=.*|MIRAKC_ARIB_VERSION=\"$VERSION\"|" >$TEMP_FILE $TARGET_FILE
+sed -r -e "s|^MIRAKC_ARIB_VERSION=.*|MIRAKC_ARIB_VERSION=\"$VERSION\"|" $TARGET_FILE >$TEMP_FILE
 mv -f $TEMP_FILE $TARGET_FILE
 
 if git diff --quiet -- $TARGET_FILE
